# Generated by Django 2.2.12 on 2020-05-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('r1', models.CharField(max_length=20)),
                ('r2', models.CharField(max_length=20)),
                ('r3', models.CharField(max_length=20)),
                ('r4', models.CharField(max_length=20)),
                ('r5', models.CharField(max_length=20)),
                ('r6', models.CharField(max_length=20)),
                ('r7', models.CharField(max_length=20)),
                ('r8', models.CharField(max_length=20)),
                ('r9', models.CharField(max_length=20)),
                ('r10', models.CharField(max_length=20)),
            ],
        ),
    ]
